import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "minimo — Invoicing without the chasing",
  description: "Create clear invoices, see what happened after sending, and make payment the easiest next step.",
  openGraph: { title: "minimo — Send invoices. Get paid. Move on.", description: "Simple invoicing for independent businesses.", type: "website" },
};

export default function MarketingPage() {
  return <main className="marketing-page">
    <header className="marketing-header"><div className="wordmark"><span className="wordmark-mark" />minimo</div><nav><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><Link href="/auth/sign-in">Sign in</Link><Link className="button primary" href="/onboarding">Get started</Link></nav></header>
    <section className="marketing-hero"><div className="hero-copy"><div className="eyebrow">Invoicing without the chasing</div><h1>Send invoices.<br /><span>Get paid. Move on.</span></h1><p>minimo helps independent businesses create clear invoices, see what happened after sending, and make payment the easiest next step.</p><div className="button-row marketing-buttons"><Link className="button primary" href="/onboarding">Create your first invoice</Link><a className="button secondary" href="#how-it-works">See how it works</a></div></div><div className="hero-card"><div className="hero-card-top"><span className="status sent">Viewed</span><span className="subtle">INV-1043</span></div><div className="hero-card-client">Maya Chen <span>Northstar Studio</span></div><div className="hero-card-amount">$1,850.00</div><div className="hero-card-due">Due September 1, 2026</div><div className="hero-card-progress"><span className="done">Sent</span><span className="done">Viewed</span><span>Paid</span></div><Link className="button primary" style={{ width: "100%" }} href="/i/demo-inv-1043">Pay invoice</Link></div></section>
    <section className="trust-strip"><span>Simple by design</span><span>Secure payment handoff</span><span>Exportable invoices</span><span>Mobile-first flow</span></section>
    <section className="marketing-section" id="how-it-works"><div className="section-heading"><div><div className="eyebrow">The whole loop, in one place</div><h2>Less uncertainty between sending and getting paid.</h2></div><p className="subtle">minimo keeps the important moments visible without turning invoicing into accounting homework.</p></div><div className="benefit-grid"><Benefit number="01" title="Create quickly" body="Start with helpful defaults, add your work, and see a professional invoice as you build it." /><Benefit number="02" title="Know what happened" body="Follow delivery, invoice views, reminders, and payment status in a calm timeline." /><Benefit number="03" title="Follow up politely" body="Use a clear reminder schedule so overdue invoices do not depend on awkward manual chasing." /></div></section>
    <section className="marketing-callout"><div><div className="eyebrow">Built for independent work</div><h2>Your work is personal. Getting paid should feel straightforward.</h2></div><Link className="button primary" href="/onboarding">Try the prototype</Link></section>
    <section className="marketing-section pricing-section" id="pricing"><div className="eyebrow">Pricing that stays clear</div><h2>Start simple. Keep your records yours.</h2><div className="pricing-grid"><PricingCard title="Free" price="$0" suffix="forever" items={["5 newly issued invoices each month", "Unlimited drafts and clients", "PDF downloads and data export", "minimo branding included"]} /><PricingCard title="Pro" price="$9" suffix="/ month" featured items={["Reasonable fair-use invoice issuance", "Custom reminder schedules", "Remove minimo branding", "Priority support"]} /></div></section>
    <section className="marketing-section faq-section"><div className="eyebrow">Good to know</div><h2>Questions, answered simply.</h2><div className="faq-list"><details><summary>Do my clients need a minimo account?</summary><p className="subtle">No. Clients can open and pay an invoice through its secure link without creating an account.</p></details><details><summary>Can I export my data?</summary><p className="subtle">Yes. PDF downloads and data export are available on both Free and Pro.</p></details><details><summary>Does minimo hold my clients’ money?</summary><p className="subtle">No. Online payments use Stripe-hosted payment surfaces and move directly to the connected seller account.</p></details></div></section>
    <footer className="marketing-footer"><div className="wordmark"><span className="wordmark-mark" />minimo</div><span>Send invoices. Get paid. Move on.</span><div className="footer-links"><Link href="/legal/terms">Terms</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/acceptable-use">Acceptable use</Link><Link href="/legal/cookies">Cookies</Link><Link href="/legal/subprocessors">Subprocessors</Link></div><span>© 2026 minimo</span></footer>
  </main>;
}

function Benefit({ number, title, body }: { number: string; title: string; body: string }) { return <article className="benefit-card"><span className="benefit-number">{number}</span><h3>{title}</h3><p className="subtle">{body}</p></article>; }

function PricingCard({ title, price, suffix, items, featured = false }: { title: string; price: string; suffix: string; items: string[]; featured?: boolean }) { return <article className={`pricing-card${featured ? " featured" : ""}`}><div className="pricing-card-top"><h3>{title}</h3><span className="pricing-price">{price} <small>{suffix}</small></span></div><p className="subtle">{featured ? "More flexibility as your independent work grows." : "A calm place to start sending professional invoices."}</p><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><Link className={`button ${featured ? "primary" : "secondary"}`} href="/onboarding">{featured ? "Try the prototype" : "Start free"}</Link></article>; }
